In [2]:
import requests
import pandas as pd
from bs4 import BeautifulSoup

/tmp/ipykernel_4764/1781237093.py:2: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

In [2]:
base = "https://totas.cosmos.esa.int/"

In [11]:
metadata = pd.read_csv("metadata.csv")
metadata

,Link,FileName,ExposureBegin,ExposureTime,CcdTemperature,BackgroundMean,BackgroundSigma,RightAscension,Declination,Angle,...,OffsetDeclination,Offset,X,Y,Flux,RightAscension.1,Declination.1,Magnitude,Name,id
0,image.php?id=302591,T030030_01510151_3_C_08551+2850_240114_232709.fit,2024-01-14 23:27:09,30,,3203.989014,78.248138,8.901213,28.685240,0.181138,...,13.614371,23.092761,815.898585,783.063679,424,8.892341,28.579975,20.001883,TO1E174,302591
1,image.php?id=302590,T030030_01510151_3_B_08551+2850_240114_231019.fit,2024-01-14 23:10:19,30,,3880.415527,85.984711,8.901200,28.684677,0.183106,...,13.580603,23.080949,809.079618,783.337580,314,8.892531,28.579180,20.128754,TO1E174,302590
2,image.php?id=302868,T030030_01520154_3_D_09098+2937_240114_234719.fit,2024-01-14 23:47:19,30,,3114.849365,231.468170,9.145611,29.473146,0.133846,...,13.888737,23.735318,675.591678,684.429129,769,9.140803,29.406079,19.510056,TO1E173,302868
3,image.php?id=302866,T030030_01520154_3_B_09098+2937_240114_231339.fit,2024-01-14 23:13:39,30,,4140.000000,218.997269,9.145645,29.473827,0.123743,...,13.929647,23.737028,664.718346,693.472868,387,9.141159,29.403325,19.945290,TO1E173,302866
4,image.php?id=302868,T030030_01520154_3_D_09098+2937_240114_234719.fit,2024-01-14 23:47:19,30,,3114.849365,231.468170,9.145611,29.473146,0.133846,...,13.888737,23.735318,678.926326,562.193517,1018,9.140702,29.453232,19.205502,TO1E172,302868
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25333,image.php?id=261435,T026035_01320179_2_A_09366+1333_210210_003449.fit,2021-02-10 00:34:49,30,,1444.216919,53.566090,9.603859,13.613007,-0.037215,...,2.280430,7.870825,188.984277,188.427673,318,9.612415,13.737197,20.902592,TL29678,261435
25334,image.php?id=261584,T026035_01330177_1_B_09320+1359_210210_005259.fit,2021-02-10 00:52:59,30,,1394.772095,51.729767,9.527342,13.998540,0.007475,...,-0.587615,4.424734,1017.149444,752.322734,1258,9.513946,13.905275,19.550474,TL29677,261584
25335,image.php?id=261583,T026035_01330177_1_A_09320+1359_210210_003609.fit,2021-02-10 00:36:09,30,,1371.091919,51.431904,9.527391,13.999379,0.023737,...,-0.537233,4.460905,1011.458879,757.608411,1070,9.514144,13.904070,19.748404,TL29677,261583
25336,image.php?id=261586,T026035_01330177_1_D_09320+1359_210210_012639.fit,2021-02-10 01:26:39,30,,1404.202148,51.761360,9.527272,13.998356,0.019470,...,-0.598662,4.365861,391.471074,894.936639,363,9.530474,13.850111,20.905769,TL29676,261586
25337,image.php?id=261583,T026035_01330177_1_A_09320+1359_210210_003609.fit,2021-02-10 00:36:09,30,,1371.091919,51.431904,9.527391,13.999379,0.023737,...,-0.537233,4.460905,373.499127,902.109948,573,9.531070,13.848416,20.426477,TL29676,261583

In [30]:
endpoint = metadata["Link"][4]
url = base + endpoint
id_ = metadata["id"][4]

In [24]:
r = requests.get(url, headers={"Cookie": "PHPSESSID=41d61821d1c671383cca68df56573419"})
soup = BeautifulSoup(r.content, "html.parser")

In [25]:
print(soup.prettify())

<html>
 <head>
  <meta content="text/html; charset=utf-8" http-equiv="Content-Type"/>
  <title>
   TOTAS
  </title>
  <link crossorigin="anonymous" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" rel="stylesheet"/>
  <link href="css/totas.css" rel="stylesheet" type="text/css"/>
 </head>
 <body>
  <table border="0" cellpadding="0" cellspacing="0" height="70">
   <tr>
    <td width="210">
     <a href="http://www.iac.es/eno.php?op1=3&amp;op2=6&amp;lang=en&amp;id=7" target="_blank">
      <img alt="OGS" border="0" height="130" src="images/ogs.jpg" width="232"/>
     </a>
    </td>
    <td width="100%">
     <center>
      <h3>
       TOTAS
      </h3>
      <h4>
       Teide Observatory Tenerife Asteroid Survey
      </h4>
      <a href="team.php">
       Team
      </a>
      <a href="http://www.kleinplanetenseite.de/Statistik_mpl/J04_eng/J04_eng.htm" target="_blank">
       Statistics
      </a>
      <a href="http://www.esa.int/Enabling_Support/Operations/Amateur_skywatchers_help_space_hazards_team" target="_blank">
       ESA story (1)
      </a>
      <a href="http://www.esa.int/Enabling_Support/Operations/Amateur_skywatchers_help_space_hazards_team_continuation" target="_blank">
       (2)
      </a>
      <a href="mpecs.php">
       MPECs
      </a>
      <a href="https://www.sky-live.tv/liveimages/webcam/opensky/cam13-IAC-OT-PNteide-CAN.jpg" target="_blank">
       SkyCam
      </a>
      <a href="http://de.sat24.com/de/ce?type=infrapolair" target="_blank">
       Clouds
      </a>
      <a href="https://cww.ot-admin.net/v2/d/cww_ot/common-weather-website-of-teide-observatory" target="_blank">
       Weather 1
      </a>
      <a href="http://song.phys.au.dk/tenerife/weatherpage/" target="_blank">
       Weather 2
      </a>
      <a href="https://kachelmannwetter.com/de/wetter/12172641-teide-observatory" target="_blank">
       Weather 3
      </a>
      <a href="https://research.iac.es/proyecto/site-testing/dimma/ot/datos4.php" target="_blank">
       Seeing
      </a>
      <a href="https://www.wetterzentrale.de/maps/MS_-1728eur_g05.png" target="_blank">
       Meteogram
      </a>
     </center>
    </td>
    <td width="210">
     <a href="http://en.wikipedia.org/wiki/Teide" target="_blank">
      <img alt="Pico del Teide" border="0" height="130" src="images/teide.jpg" width="372"/>
     </a>
    </td>
   </tr>
  </table>
  <hr/>
  <table width="100%">
   <tr>
    <td valign="top">
     <a href="search.php">
      <img border="0" src="images/search.png"/>
      Search
     </a>
    </td>
    <td align="right">
     <small>
      [
      <a href="user.php?id=73">
       Robin Jehn
      </a>
      ]
      <a href="includes/logout.inc.php">
       Logout
      </a>
     </small>
    </td>
   </tr>
  </table>
  <p>
   <a href="index.php?list=Nights">
    Overview
   </a>
   <a href="mover.php?nextunconfirmed=1">
    KLICKEN!
   </a>
   <br/>
   <br/>
   <p>
    Observing Run:
    <a href="observingrun.php?id=137">
     SSA-NEO Slot #144 (3 nights)
    </a>
    <small>
     starting 2024-01-08
    </small>
    <br/>
    Night:
    <a href="night.php?id=403">
     2024-01-14
    </a>
    <br/>
    Region:
    <a href="region.php?id=844">
     030 030
    </a>
    <br/>
    Field:
    <a href="field.php?id=79032">
     0152 0154 / CCD 3
    </a>
    <br/>
    <h3>
     Image T030030_01520154_3_D_09098+2937_240114_234719.fit
    </h3>
    <p>
     11 Movers:
     <span style="color:green">
      new! =&gt;
     </span>
     <a href="/image.php?id=302868&amp;moverimages=1">
      Mover Images
     </a>
     <p>
      <table border="1" cellpadding="2" cellspacing="0" class="list">
       <tr>
        <th>
         SohasDesignation
        </th>
        <th>
         Asteroid
        </th>
        <th>
         AutoDetected
        </th>
        <th>
         Confirmed
        </th>
        <th>
         ConfirmedAt
        </th>
        <th>
         ConfirmedBy
        </th>
        <th>
         Comment
        </th>
       </tr>
       <tr class="odd">
        <td style="white-space:nowrap">
         <a href="mover.php?id=546700">
          TO1E173
         </a>
        </td>
        <td>
         <a href="asteroid.php?id=">
         </a>
        </td>
        <td>
        </td>
        <td>
         1
        </td>
        <td>
         2024-02-01 20:40:06
        </td>
        <td>
         <a href="user.php?id=71">
          Zlatko Orbanic
         </a>
        </td>
        <td>
        </td>
       </tr>
       <tr class="even">
        <td style="white-space:nowrap">
         <a href="mover.php?id=546699">
          TO1E172
         </a>
        </td>
        <td>
         <a href="asteroid.php?id=">
         </a>
        </td>
        <td>
        </td>
        <td>
         1
        </td>
        <td>
         2024-02-01 20:39:38
        </td>
        <td>
         <a href="user.php?id=71">
          Zlatko Orbanic
         </a>
        </td>
        <td>
        </td>
       </tr>
       <tr class="odd">
        <td style="white-space:nowrap">
         <a href="mover.php?id=546390">
          M332248
         </a>
        </td>
        <td>
         <a href="asteroid.php?id=">
         </a>
        </td>
        <td>
         1
        </td>
        <td>
         2
        </td>
        <td>
         2024-01-15 11:06:25
        </td>
        <td>
         <a href="user.php?id=31">
          Tobias Thommes
         </a>
        </td>
        <td>
        </td>
       </tr>
       <tr class="even">
        <td style="white-space:nowrap">
         <a href="mover.php?id=546389">
          M332247
         </a>
        </td>
        <td>
         <a href="asteroid.php?id=">
         </a>
        </td>
        <td>
         1
        </td>
        <td>
         2
        </td>
        <td>
         2024-01-15 11:06:23
        </td>
        <td>
         <a href="user.php?id=47">
          Michal Biesiada
         </a>
        </td>
        <td>
        </td>
       </tr>
       <tr class="odd">
        <td style="white-space:nowrap">
         <a href="mover.php?id=546388">
          M332246
         </a>
        </td>
        <td>
         <a href="asteroid.php?id=">
         </a>
        </td>
        <td>
         1
        </td>
        <td>
         2
        </td>
        <td>
         2024-01-15 11:06:27
        </td>
        <td>
         <a href="user.php?id=12">
          Harald Bill
         </a>
        </td>
        <td>
        </td>
       </tr>
       <tr class="even">
        <td style="white-space:nowrap">
         <a href="mover.php?id=546387">
          M332245
         </a>
        </td>
        <td>
         <a href="asteroid.php?id=">
         </a>
        </td>
        <td>
         1
        </td>
        <td>
         2
        </td>
        <td>
         2024-01-15 11:06:17
        </td>
        <td>
         <a href="user.php?id=31">
          Tobias Thommes
         </a>
        </td>
        <td>
        </td>
       </tr>
       <tr class="odd">
        <td style="white-space:nowrap">
         <a href="mover.php?id=546386">
          M332244
         </a>
        </td>
        <td>
         <a href="asteroid.php?id=">
         </a>
        </td>
        <td>
         1
        </td>
        <td>
         2
        </td>
        <td>
         2024-01-15 11:06:20
        </td>
        <td>
         <a href="user.php?id=71">
          Zlatko Orbanic
         </a>
        </td>
        <td>
        </td>
       </tr>
       <tr class="even">
        <td style="white-space:nowrap">
         <a href="mover.php?id=546384">
          M332242
         </a>
        </td>
        <td>
         <a href="asteroid.php?id=">
         </a>
        </td>
        <td>
         1
        </td>
        <td>
         2
        </td>
        <td>
         2024-01-15 11:06:16
        </td>
        <td>
         <a href="user.php?id=47">
          Michal Biesiada
         </a>
        </td>
        <td>
        </td>
       </tr>
       <tr class="odd">
        <td style="white-space:nowrap">
         <a href="mover.php?id=546383">
          M332241
         </a>
        </td>
        <td>
         <a href="asteroid.php?id=">
         </a>
        </td>
        <td>
         1
        </td>
        <td>
         2
        </td>
        <td>
         2024-01-15 11:06:17
        </td>
        <td>
         <a href="user.php?id=12">
          Harald Bill
         </a>
        </td>
        <td>
        </td>
       </tr>
       <tr class="even">
        <td style="white-space:nowrap">
         <a href="mover.php?id=546382">
          M332240
         </a>
        </td>
        <td>
         <a href="asteroid.php?id=">
         </a>
        </td>
        <td>
         1
        </td>
        <td>
         2
        </td>
        <td>
         2024-01-15 11:06:12
        </td>
        <td>
         <a href="user.php?id=66">
          Dieter Husar
         </a>
        </td>
        <td>
        </td>
       </tr>
       <tr class="odd">
        <td style="white-space:nowrap">
         <a href="mover.php?id=546381">
          M332239
         </a>
        </td>
        <td>
         <a href="asteroid.php?id=">
         </a>
        </td>
        <td>
         1
        </td>
        <td>
         2
        </td>
        <td>
         2024-01-15 11:06:09
        </td>
        <td>
         <a href="user.php?id=12">
          Harald Bill
         </a>
        </td>
        <td>
        </td>
       </tr>
      </table>
      <br/>
      <br/>
      <p>
       2 Positions:
       <p>
        <table border="1" cellpadding="2" cellspacing="0" class="list">
         <tr>
          <th>
           MpcLine
          </th>
          <th>
           X
          </th>
          <th>
           Y
          </th>
          <th>
           Flux
          </th>
          <th>
           RightAscension
          </th>
          <th>
           Declination
          </th>
          <th>
           Magnitude
          </th>
         </tr>
         <tr class="odd">
          <td style="white-space:nowrap">
           <a href="position.php?id=1894735">
            TO1E173  C2024 01 14.99137 09 08 26.89 +29 24 21.9          19.5 R      J04
           </a>
          </td>
          <td>
           675.591677503251
          </td>
          <td>
           684.429128738622
          </td>
          <td>
           769
          </td>
          <td>
           9.1408028232208
          </td>
          <td>
           29.4060792886037
          </td>
          <td>
           19.5100555419922
          </td>
         </tr>
         <tr class="even">
          <td style="white-space:nowrap">
           <a href="position.php?id=1894733">
            TO1E172  C2024 01 14.99137 09 08 26.53 +29 27 11.6          19.2 R      J04
           </a>
          </td>
          <td>
           678.926326129666
          </td>
          <td>
           562.193516699411
          </td>
          <td>
           1018
          </td>
          <td>
           9.14070178781949
          </td>
          <td>
           29.4532324571481
          </td>
          <td>
           19.2055015563965
          </td>
         </tr>
        </table>
        <br/>
        <p>
         5 Measurers:
         <p>
          <table border="1" cellpadding="2" cellspacing="0" class="list">
           <tr>
            <th>
             LastName
            </th>
            <th>
             FirstName
            </th>
            <th>
             Overall Activity
            </th>
            <th>
             Clicks
            </th>
            <th>
             Rejected
            </th>
            <th>
             Confirmed
            </th>
            <th>
             Maybe
            </th>
            <th>
             Manual
            </th>
           </tr>
           <tr class="odd">
            <td style="white-space:nowrap">
             <a href="user.php?id=71">
              Orbanic
             </a>
            </td>
            <td>
             Zlatko
            </td>
            <td>
             7
            </td>
            <td>
             1
            </td>
            <td>
             1
            </td>
            <td>
             0
            </td>
            <td>
             0
            </td>
            <td>
             2
            </td>
           </tr>
           <tr class="even">
            <td style="white-space:nowrap">
             <a href="user.php?id=12">
              Bill
             </a>
            </td>
            <td>
             Harald
            </td>
            <td>
             3
            </td>
            <td>
             3
            </td>
            <td>
             3
            </td>
            <td>
             0
            </td>
            <td>
             0
            </td>
            <td>
             0
            </td>
           </tr>
           <tr class="odd">
            <td style="white-space:nowrap">
             <a href="user.php?id=47">
              Biesiada
             </a>
            </td>
            <td>
             Michal
            </td>
            <td>
             2
            </td>
            <td>
             2
            </td>
            <td>
             2
            </td>
            <td>
             0
            </td>
            <td>
             0
            </td>
            <td>
             0
            </td>
           </tr>
           <tr class="even">
            <td style="white-space:nowrap">
             <a href="user.php?id=31">
              Thommes
             </a>
            </td>
            <td>
             Tobias
            </td>
            <td>
             2
            </td>
            <td>
             2
            </td>
            <td>
             2
            </td>
            <td>
             0
            </td>
            <td>
             0
            </td>
            <td>
             0
            </td>
           </tr>
           <tr class="odd">
            <td style="white-space:nowrap">
             <a href="user.php?id=66">
              Husar
             </a>
            </td>
            <td>
             Dieter
            </td>
            <td>
             1
            </td>
            <td>
             1
            </td>
            <td>
             1
            </td>
            <td>
             0
            </td>
            <td>
             0
            </td>
            <td>
             0
            </td>
           </tr>
          </table>
          <br/>
          <br/>
          <img height="1024" src="image-view.php?file=2024/01/14/030030/images/image302868.png" style="position:relative;top:0px;left:0px" width="1024"/>
         </p>
        </p>
       </p>
      </p>
     </p>
    </p>
   </p>
  </p>
 </body>
</html>

In [31]:
import os

os.system(
    f"wget https://totas.cosmos.esa.int/image-view.php?file=2024/01/14/030030/images/image302868.png -O images/{id_}.png"
)

--2024-02-05 16:06:47--  https://totas.cosmos.esa.int/image-view.php?file=2024/01/14/030030/images/image302868.png
Resolving totas.cosmos.esa.int (totas.cosmos.esa.int)... 195.169.141.82
Connecting to totas.cosmos.esa.int (totas.cosmos.esa.int)|195.169.141.82|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1038001 (1014K) [image/png]
Saving to: ‘images/302868.png’

     0K .......... .......... .......... .......... ..........  4%  486K 2s
    50K .......... .......... .......... .......... ..........  9%  291K 3s
   100K .......... .......... .......... .......... .......... 14%  889K 2s
   150K .......... .......... .......... .......... .......... 19%  939K 2s
   200K .......... .......... .......... .......... .......... 24%  553K 1s
   250K .......... .......... .......... .......... .......... 29% 1.06M 1s
   300K .......... .......... .......... .......... .......... 34% 1.08M 1s
   350K .......... .......... .......... .......... .......... 39% 1.05M 1s
   400K .......... .......... .......... .......... .......... 44% 4.76M 1s
   450K .......... .......... .......... .......... .......... 49% 1.05M 1s
   500K .......... .......... .......... .......... .......... 54% 1.07M 1s
   550K .......... .......... .......... .......... .......... 59% 1.06M 1s
   600K .......... .......... .......... .......... .......... 64% 9.13M 0s
   650K .......... .......... .......... .......... .......... 69% 1.15M 0s
   700K .......... .......... .......... .......... .......... 73% 1.10M 0s
   750K .......... .......... .......... .......... .......... 78% 4.38M 0s
   800K .......... .......... .......... .......... .......... 83%  914K 0s
   850K .......... .......... .......... .......... .......... 88% 1.66M 0s
   900K .......... .......... .......... .......... .......... 93% 2.97M 0s
   950K .......... .......... .......... .......... .......... 98% 1.64M 0s
  1000K .......... ...                                        100%  823K=1.0s

2024-02-05 16:06:48 (1003 KB/s) - ‘images/302868.png’ saved [1038001/1038001]

0

In [22]:
soup.findAll("img")

[<img alt="OGS" border="0" height="130" src="images/ogs.jpg" width="232"/>,
 <img alt="Pico del Teide" border="0" height="130" src="images/teide.jpg" width="372"/>,
 <img border="0" src="images/search.png"/>]

In [40]:
# WRite a function to get the image
def get_image(url, id_):
    r = requests.get(
        url, headers={"Cookie": "PHPSESSID=41d61821d1c671383cca68df56573419"}
    )
    soup = BeautifulSoup(r.content, "html.parser")
    img = soup.findAll("img")[-1]
    img_url = base + img["src"]
    os.system(f"wget {img_url} -O images/{id_}.png")

In [41]:
# Test the function
get_image(url, id_)

--2024-02-05 16:08:55--  https://totas.cosmos.esa.int/image-view.php?file=2024/01/14/030030/images/image302868.png
Resolving totas.cosmos.esa.int (totas.cosmos.esa.int)... 195.169.141.82
Connecting to totas.cosmos.esa.int (totas.cosmos.esa.int)|195.169.141.82|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1038001 (1014K) [image/png]
Saving to: ‘images/302868.png’

     0K .......... .......... .......... .......... ..........  4%  500K 2s
    50K .......... .......... .......... .......... ..........  9%  532K 2s
   100K .......... .......... .......... .......... .......... 14%  974K 1s
   150K .......... .......... .......... .......... .......... 19%  631K 1s
   200K .......... .......... .......... .......... .......... 24% 1.09M 1s
   250K .......... .......... .......... .......... .......... 29% 1.12M 1s
   300K .......... .......... .......... .......... .......... 34% 1.07M 1s
   350K .......... .......... .......... .......... .......... 39% 4.31M 1s
   400K .......... .......... .......... .......... .......... 44% 1.29M 1s
   450K .......... .......... .......... .......... .......... 49% 1.15M 1s
   500K .......... .......... .......... .......... .......... 54% 1.16M 0s
   550K .......... .......... .......... .......... .......... 59% 4.77M 0s
   600K .......... .......... .......... .......... .......... 64% 1.08M 0s
   650K .......... .......... .......... .......... .......... 69% 1.24M 0s
   700K .......... .......... .......... .......... .......... 73% 8.49M 0s
   750K .......... .......... .......... .......... .......... 78% 1.20M 0s
   800K .......... .......... .......... .......... .......... 83%  870K 0s
   850K .......... .......... .......... .......... .......... 88%  137M 0s
   900K .......... .......... .......... .......... .......... 93% 1.07M 0s
   950K .......... .......... .......... .......... .......... 98% 10.3M 0s
  1000K .......... ...                                        100%  373K=0.9s

2024-02-05 16:08:56 (1.13 MB/s) - ‘images/302868.png’ saved [1038001/1038001]

In [3]:
url = "https://totas.cosmos.esa.int/mover.php?id=89000"
r = requests.get(url)
soup = BeautifulSoup(r.content, "html.parser")

In [4]:
print(soup.prettify())

<html>
 <head>
  <meta content="text/html; charset=utf-8" http-equiv="Content-Type"/>
  <title>
   TOTAS
  </title>
  <link crossorigin="anonymous" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" rel="stylesheet"/>
  <link href="css/totas.css" rel="stylesheet" type="text/css"/>
 </head>
 <body>
  <table border="0" cellpadding="0" cellspacing="0" height="70">
   <tr>
    <td width="210">
     <a href="http://www.iac.es/eno.php?op1=3&amp;op2=6&amp;lang=en&amp;id=7" target="_blank">
      <img alt="OGS" border="0" height="130" src="images/ogs.jpg" width="232"/>
     </a>
    </td>
    <td width="100%">
     <center>
      <h3>
       TOTAS
      </h3>
      <h4>
       Teide Observatory Tenerife Asteroid Survey
      </h4>
      <a href="team.php">
       Team
      </a>
      <a href="http://www.kleinplanetenseite.de/Statistik_mpl/J04_eng/J04_eng.htm" target="_blank">
       Statistics
      </a>
      <a href="http://www.esa.int/Enabling_Support/Operations/Amateur_skywatchers_help_space_hazards_team" target="_blank">
       ESA story (1)
      </a>
      <a href="http://www.esa.int/Enabling_Support/Operations/Amateur_skywatchers_help_space_hazards_team_continuation" target="_blank">
       (2)
      </a>
      <a href="mpecs.php">
       MPECs
      </a>
      <a href="https://www.sky-live.tv/liveimages/webcam/opensky/cam13-IAC-OT-PNteide-CAN.jpg" target="_blank">
       SkyCam
      </a>
      <a href="http://de.sat24.com/de/ce?type=infrapolair" target="_blank">
       Clouds
      </a>
      <a href="https://cww.ot-admin.net/v2/d/cww_ot/common-weather-website-of-teide-observatory" target="_blank">
       Weather 1
      </a>
      <a href="http://song.phys.au.dk/tenerife/weatherpage/" target="_blank">
       Weather 2
      </a>
      <a href="https://kachelmannwetter.com/de/wetter/12172641-teide-observatory" target="_blank">
       Weather 3
      </a>
      <a href="https://research.iac.es/proyecto/site-testing/dimma/ot/datos4.php" target="_blank">
       Seeing
      </a>
      <a href="https://www.wetterzentrale.de/maps/MS_-1728eur_g05.png" target="_blank">
       Meteogram
      </a>
     </center>
    </td>
    <td width="210">
     <a href="http://en.wikipedia.org/wiki/Teide" target="_blank">
      <img alt="Pico del Teide" border="0" height="130" src="images/teide.jpg" width="372"/>
     </a>
    </td>
   </tr>
  </table>
  <hr/>
  <table width="100%">
   <tr>
    <td valign="top">
     <a href="search.php">
      <img border="0" src="images/search.png"/>
      Search
     </a>
    </td>
    <td align="right">
     <small>
      [Guest]
      <a href="login.php">
       Login
      </a>
     </small>
    </td>
   </tr>
  </table>
  <p>
   <a href="index.php?list=Nights">
    Overview
   </a>
   <br/>
   <p>
    Observing Run:
    <a href="observingrun.php?id=20">
     SSA-NEO Slot #25
    </a>
    <small>
     starting 2011-10-28
    </small>
    <br/>
    Night:
    <a href="night.php?id=46">
     2011-10-28
    </a>
    <small>
     Observer: Pablo
    </small>
    <br/>
    Region:
    <a href="region.php?id=106">
     031 014
    </a>
    <small>
    </small>
    <br/>
    Field:
    <a href="field.php?id=9410">
     0158 0072 / CCD 1
    </a>
    <small>
    </small>
    <br/>
    <h3>
     Mover OGS2031 - real asteroid
    </h3>
    <p class="comment">
     M078014
    </p>
    <p>
     Speed =
     <span style="color:red">
      0.52"/min
     </span>
     P.A. =
     <span style="color:green">
      242.05°
     </span>
    </p>
    <table>
     <tr>
      <tr>
       <td>
        centered on sky
       </td>
       <td>
       </td>
       <tr>
        <td>
         <img class="mi" height="44" src="image-view.php?file=2011/10/28/031014/movers/a0089000.gif" width="56"/>
        </td>
        <td>
         <div class="mi-c">
          <img class="mi" height="44" src="image-view.php?file=2011/10/28/031014/movers/a0089000-1.png" width="56"/>
          <img class="mi" height="44" src="image-view.php?file=2011/10/28/031014/movers/a0089000-2.png" width="56"/>
          <img class="mi" height="44" src="image-view.php?file=2011/10/28/031014/movers/a0089000-3.png" width="56"/>
         </div>
        </td>
       </tr>
       <tr>
        <td>
         <img class="mi" height="86" src="image-view.php?file=2011/10/28/031014/movers/a0089000.gif" width="110"/>
        </td>
        <td>
         <div class="mi-c">
          <img class="mi" height="86" src="image-view.php?file=2011/10/28/031014/movers/a0089000-1.png" width="110"/>
          <img class="mi" height="86" src="image-view.php?file=2011/10/28/031014/movers/a0089000-2.png" width="110"/>
          <img class="mi" height="86" src="image-view.php?file=2011/10/28/031014/movers/a0089000-3.png" width="110"/>
         </div>
        </td>
       </tr>
       <tr>
        <td>
         <br/>
         centered on asteroid
        </td>
       </tr>
       <tr>
        <td>
         <img class="mi" height="32" src="image-view.php?file=2011/10/28/031014/movers/b0089000.gif" width="32"/>
        </td>
        <td>
         <div class="mi-c">
          <img class="mi" height="32" src="image-view.php?file=2011/10/28/031014/movers/b0089000-1.png" width="32"/>
          <img class="mi" height="32" src="image-view.php?file=2011/10/28/031014/movers/b0089000-2.png" width="32"/>
          <img class="mi" height="32" src="image-view.php?file=2011/10/28/031014/movers/b0089000-3.png" width="32"/>
         </div>
        </td>
       </tr>
       <tr>
        <td>
         <img class="mi" height="62" src="image-view.php?file=2011/10/28/031014/movers/b0089000.gif" width="62"/>
        </td>
        <td>
         <div class="mi-c">
          <img class="mi" height="62" src="image-view.php?file=2011/10/28/031014/movers/b0089000-1.png" width="62"/>
          <img class="mi" height="62" src="image-view.php?file=2011/10/28/031014/movers/b0089000-2.png" width="62"/>
          <img class="mi" height="62" src="image-view.php?file=2011/10/28/031014/movers/b0089000-3.png" width="62"/>
         </div>
        </td>
       </tr>
      </tr>
     </tr>
    </table>
    <p>
     <small>
      Visually processed by
      <a href="user.php?id=20">
       Carolin Liefke
      </a>
      at 2011-10-29 22:23:01
     </small>
     <br/>
     <br/>
     <canvas height="90.421941609098" id="canvas89000" style="border:1px solid #555;" width="152.94486447622">
     </canvas>
     <script>
      var c = document.getElementById('canvas89000');
var ctx = c.getContext('2d');
ctx.strokeStyle = '#8f8';
ctx.beginPath();
ctx.arc(15,15,3,0,2*Math.PI);
ctx.moveTo(15,15);
ctx.lineTo(78,47);
ctx.stroke();
ctx.beginPath();
ctx.arc(78,47,3,0,2*Math.PI);
ctx.moveTo(78,47);
ctx.lineTo(138,75);
ctx.stroke();
ctx.beginPath();
ctx.arc(138,75,3,0,2*Math.PI);
ctx.stroke();
     </script>
     <p>
      3 Images:
      <p>
       <table border="1" cellpadding="2" cellspacing="0" class="list">
        <tr>
         <th>
          FileName
         </th>
         <th>
          ExposureBegin
         </th>
         <th>
          ExposureTime
         </th>
         <th>
          CcdTemperature
         </th>
         <th>
          BackgroundMean
         </th>
         <th>
          BackgroundSigma
         </th>
         <th>
          RightAscension
         </th>
         <th>
          Declination
         </th>
         <th>
          Angle
         </th>
         <th>
          Azimuth
         </th>
         <th>
          Altitude
         </th>
         <th>
          Airmass
         </th>
         <th>
          MagnitudeZeroPoint
         </th>
         <th>
          PixelScaleX
         </th>
         <th>
          PixelScaleY
         </th>
         <th>
          NumberOfDetections
         </th>
         <th>
          NumberOfStars
         </th>
         <th>
          AverageResidual
         </th>
         <th>
          RmsResidual
         </th>
         <th>
          FitOrder
         </th>
         <th>
          OffsetRightAscension
         </th>
         <th>
          OffsetDeclination
         </th>
         <th>
          Offset
         </th>
        </tr>
        <tr class="odd">
         <td style="white-space:nowrap">
          <a href="image.php?id=28205">
           T031014_01580072_1_C_03411+2216_111029_054855.fit
          </a>
         </td>
         <td>
          2011-10-29 05:48:55
         </td>
         <td>
          60
         </td>
         <td>
         </td>
         <td>
          7675.609375
         </td>
         <td>
          130.022567749023
         </td>
         <td>
          3.69172159659166
         </td>
         <td>
          22.1780260200698
         </td>
         <td>
          -0.0356687267003952
         </td>
         <td>
          95.1394386929097
         </td>
         <td>
          42.3138844214245
         </td>
         <td>
          1.48378792274885
         </td>
         <td>
          24.1283133665174
         </td>
         <td>
          -1.2448877827473
         </td>
         <td>
          -1.24476190022703
         </td>
         <td>
          1431
         </td>
         <td>
          348
         </td>
         <td>
          0.354902109699913
         </td>
         <td>
          0.418766645525998
         </td>
         <td>
          4
         </td>
         <td>
          2.64738449753068
         </td>
         <td>
          -0.151772129144591
         </td>
         <td>
          2.65170761258739
         </td>
        </tr>
        <tr class="even">
         <td style="white-space:nowrap">
          <a href="image.php?id=28204">
           T031014_01580072_1_B_03411+2216_111029_051805.fit
          </a>
         </td>
         <td>
          2011-10-29 05:18:05
         </td>
         <td>
          60
         </td>
         <td>
         </td>
         <td>
          6891.19140625
         </td>
         <td>
          123.751190185547
         </td>
         <td>
          3.69174546640432
         </td>
         <td>
          22.1784141216098
         </td>
         <td>
          -0.0461177335032579
         </td>
         <td>
          91.8996530590989
         </td>
         <td>
          49.1059426297862
         </td>
         <td>
          1.321961383869
         </td>
         <td>
          24.1310517233139
         </td>
         <td>
          -1.24474269935286
         </td>
         <td>
          -1.24446722448229
         </td>
         <td>
          1431
         </td>
         <td>
          353
         </td>
         <td>
          0.353828442549444
         </td>
         <td>
          0.417011697515434
         </td>
         <td>
          4
         </td>
         <td>
          2.66727056572166
         </td>
         <td>
          -0.128486036743559
         </td>
         <td>
          2.67034313879214
         </td>
        </tr>
        <tr class="odd">
         <td style="white-space:nowrap">
          <a href="image.php?id=28203">
           T031014_01580072_1_A_03411+2216_111029_044715.fit
          </a>
         </td>
         <td>
          2011-10-29 04:47:15
         </td>
         <td>
          60
         </td>
         <td>
         </td>
         <td>
          6668.77734375
         </td>
         <td>
          128.641555786133
         </td>
         <td>
          3.69176175723899
         </td>
         <td>
          22.1786640338168
         </td>
         <td>
          -0.0460855848349136
         </td>
         <td>
          88.2420452951045
         </td>
         <td>
          55.9106074299525
         </td>
         <td>
          1.20697321043006
         </td>
         <td>
          24.1625166340826
         </td>
         <td>
          -1.24471937703909
         </td>
         <td>
          -1.24470371900632
         </td>
         <td>
          1310
         </td>
         <td>
          351
         </td>
         <td>
          0.346987397646123
         </td>
         <td>
          0.410008808530746
         </td>
         <td>
          4
         </td>
         <td>
          2.68084276917641
         </td>
         <td>
          -0.113491304321902
         </td>
         <td>
          2.68322594001098
         </td>
        </tr>
       </table>
       <br/>
       <p>
        3 Positions:
        <p>
         <table border="1" cellpadding="2" cellspacing="0" class="list">
          <tr>
           <th>
            MpcLine
           </th>
           <th>
            X
           </th>
           <th>
            Y
           </th>
           <th>
            Flux
           </th>
           <th>
            RightAscension
           </th>
           <th>
            Declination
           </th>
           <th>
            Magnitude
           </th>
          </tr>
          <tr class="odd">
           <td style="white-space:nowrap">
            <a href="position.php?id=266016">
             OGS2031  C2011 10 29.24265 03 40 52.12 +22 10 13.7          20.3 R      J04
            </a>
           </td>
           <td>
            935.408493427705
           </td>
           <td>
            533.006572295248
           </td>
           <td>
            1978
           </td>
           <td>
            3.68114462821391
           </td>
           <td>
            22.1704670840503
           </td>
           <td>
            20.3331356048584
           </td>
          </tr>
          <tr class="even">
           <td style="white-space:nowrap">
            <a href="position.php?id=266015">
             OGS2031  C2011 10 29.22124 03 40 53.12 +22 10 20.8          20.4 R      J04
            </a>
           </td>
           <td>
            925.299561883899
           </td>
           <td>
            528.432092004381
           </td>
           <td>
            1826
           </td>
           <td>
            3.68142337016415
           </td>
           <td>
            22.1724556245474
           </td>
           <td>
            20.4226875305176
           </td>
          </tr>
          <tr class="odd">
           <td style="white-space:nowrap">
            <a href="position.php?id=266014">
             OGS2031  C2011 10 29.19982 03 40 54.17 +22 10 28.8          20.7 R      J04
            </a>
           </td>
           <td>
            914.320819112628
           </td>
           <td>
            522.819112627986
           </td>
           <td>
            1465
           </td>
           <td>
            3.6817138174013
           </td>
           <td>
            22.1746630522176
           </td>
           <td>
            20.6933097839355
           </td>
          </tr>
         </table>
         <br/>
         <p>
          Astrometry E-Mail:
          <p>
           <table border="1" cellpadding="2" cellspacing="0" class="list">
            <tr>
             <th>
              Type
             </th>
             <th>
              SentOrReceivedAt
             </th>
            </tr>
            <tr class="odd">
             <td style="white-space:nowrap">
              <a href="email.php?id=319">
               Astrometry
              </a>
             </td>
             <td>
              2011-10-30 09:25:02
             </td>
            </tr>
           </table>
           <br/>
           <p>
            <br/>
            <b>
             MPChecker query
            </b>
            of 2011-10-30 02:00:22 :
            <br/>
            <div class="mp-checker">
             <hr/>
             <p>
              The following objects, brighter than
              <i>
               V
              </i>
              = 22.0, were found in the  20.0-arcminute region around the following observation:
              <pre>
     M078014  C2011 10 29.19982 03 40 54.17 +22 10 28.8          20.7 R      J04
</pre>
              <pre>
 Object designation         R.A.      Decl.     V       Offsets     Motion/min  Orbit  <a href="http://www.cfa.harvard.edu/iau/info/FurtherObs.html">Further observations?</a>
                           h  m  s     °  '  "        R.A.   Decl.  Mot.   PA          Comment (Elong/Decl/V at date 1)

(291582) 2006 FL53       03 40 38.3 +22 18 29  21.3   3.7W   8.0N    0.5 258.3     7o  None needed at this time.
         2005 UQ210      03 41 34.7 +22 02 14  21.3   9.4E   8.2S    0.6 262.3    26d  Leave for survey recovery.
(287149) 2002 RM228      03 41 48.8 +22 17 24  19.8  12.6E   6.9N    0.5 279.4     5o  None needed at this time.
(215325) 2001 TG204      03 41 11.9 +21 56 36  19.8   4.1E  13.9S    0.5 277.4     7o  None needed at this time.
(171595) 1999 XM44       03 41 52.3 +22 17 53  18.5  13.5E   7.4N    0.5 254.1     6o  None needed at this time.
         2010 DK17       03 41 27.1 +21 55 20         7.6E  15.2S    0.7 229.8     1d  Leave for survey recovery.
         2011 UM53       03 40 49.2 +22 27 44  20.8   1.1W  17.2N    0.5 253.1     6d  Desirable between 2011 Nov. 7-13.  (167.4,+21.9,20.5)
         2002 ET133      03 41 50.4 +22 24 21  20.3  13.0E  13.9N    0.5 254.8     5o  Very desirable between 2011 Nov. 21-Dec. 21.  (174.1,+20.7,19.9)
 (50083) 2000 AG89       03 40 39.9 +21 50 49  18.9   3.3W  19.7S    0.5 256.8    10o  None needed at this time.
 </pre>
              <p>
               <hr/>
               <p>
                Number of objects checked =  546467
                <p>
                 <hr/>
                </p>
               </p>
              </p>
             </p>
            </div>
            <p>
             <br/>
             <b>
              NEO Rating query
             </b>
             of 2011-10-30 02:00:22 :
             <br/>
             <pre class="neo-rating">Digest2 version 0.11 -- Released Jun 28 2011 -- Compiled Jun 28 2011
Desig.    RMS Int NEO N22 N18 Other Possibilities
M078014  0.27   1   1   0   0 (MC 1) (MB1 49) (Pal &lt;1) (Han &lt;1) (MB2 37) (MB3 8) (JFC &lt;1)

Note on output:

The relevant entry for deciding whether to report an object as potentially
interesting is the Int score.  This is the percentage probability that
the object is an MPC interesting object; that is, one that would have a
discovery MPEC.  Objects with scores of 50 or more are posted to the NEOCP.

Documentation on the underlying program can be viewed at
<a href="https://code.google.com/p/digest2/source/browse/c/README">https://code.google.com/p/digest2/source/browse/c/README</a>
</pre>
            </p>
           </p>
          </p>
         </p>
        </p>
       </p>
      </p>
     </p>
    </p>
   </p>
  </p>
 </body>
</html>

In [5]:
soup.findAll("h3")

In [6]:
contents = soup.findAll("tr")

In [7]:
for i, content in enumerate(contents):
    if content.find("td").find("br"):
        print(i)
        print(content)
        break

6
<tr>
<td><br/>centered on asteroid</td></tr>

In [8]:
contents[7].findAll("img")[1:]

[<img class="mi" height="32" src="image-view.php?file=2011/10/28/031014/movers/b0089000-1.png" width="32"/>,
 <img class="mi" height="32" src="image-view.php?file=2011/10/28/031014/movers/b0089000-2.png" width="32"/>,
 <img class="mi" height="32" src="image-view.php?file=2011/10/28/031014/movers/b0089000-3.png" width="32"/>]

In [9]:
metadata_tables = soup.findAll("tr")
image_tables = [i for i in metadata_tables if ".fit" in i.text]
image_paths = [[j.text for j in i.findAll("td")] for i in image_tables]

In [10]:
image_tables

[<tr class="odd"><td style="white-space:nowrap"><a href="image.php?id=28205">T031014_01580072_1_C_03411+2216_111029_054855.fit</a></td><td>2011-10-29 05:48:55</td><td>60</td><td> </td><td>7675.609375</td><td>130.022567749023</td><td>3.69172159659166</td><td>22.1780260200698</td><td>-0.0356687267003952</td><td>95.1394386929097</td><td>42.3138844214245</td><td>1.48378792274885</td><td>24.1283133665174</td><td>-1.2448877827473</td><td>-1.24476190022703</td><td>1431</td><td>348</td><td>0.354902109699913</td><td>0.418766645525998</td><td>4</td><td>2.64738449753068</td><td>-0.151772129144591</td><td>2.65170761258739</td></tr>,
 <tr class="even"><td style="white-space:nowrap"><a href="image.php?id=28204">T031014_01580072_1_B_03411+2216_111029_051805.fit</a></td><td>2011-10-29 05:18:05</td><td>60</td><td> </td><td>6891.19140625</td><td>123.751190185547</td><td>3.69174546640432</td><td>22.1784141216098</td><td>-0.0461177335032579</td><td>91.8996530590989</td><td>49.1059426297862</td><td>1.321961383869</td><td>24.1310517233139</td><td>-1.24474269935286</td><td>-1.24446722448229</td><td>1431</td><td>353</td><td>0.353828442549444</td><td>0.417011697515434</td><td>4</td><td>2.66727056572166</td><td>-0.128486036743559</td><td>2.67034313879214</td></tr>,
 <tr class="odd"><td style="white-space:nowrap"><a href="image.php?id=28203">T031014_01580072_1_A_03411+2216_111029_044715.fit</a></td><td>2011-10-29 04:47:15</td><td>60</td><td> </td><td>6668.77734375</td><td>128.641555786133</td><td>3.69176175723899</td><td>22.1786640338168</td><td>-0.0460855848349136</td><td>88.2420452951045</td><td>55.9106074299525</td><td>1.20697321043006</td><td>24.1625166340826</td><td>-1.24471937703909</td><td>-1.24470371900632</td><td>1310</td><td>351</td><td>0.346987397646123</td><td>0.410008808530746</td><td>4</td><td>2.68084276917641</td><td>-0.113491304321902</td><td>2.68322594001098</td></tr>]

In [11]:
position_tables = [
    list(map(lambda x: x.text, i.findAll("td")[1:]))
    for i in metadata_tables
    if "position" in str(i)
]

In [12]:
position_tables

[['935.408493427705',
  '533.006572295248',
  '1978',
  '3.68114462821391',
  '22.1704670840503',
  '20.3331356048584'],
 ['925.299561883899',
  '528.432092004381',
  '1826',
  '3.68142337016415',
  '22.1724556245474',
  '20.4226875305176'],
 ['914.320819112628',
  '522.819112627986',
  '1465',
  '3.6817138174013',
  '22.1746630522176',
  '20.6933097839355']]

How to handle bad request

In [13]:
bad_request = "https://totas.cosmos.esa.int/mover.php?id=10000000"
br = requests.get(bad_request)
soup = BeautifulSoup(br.content, "html.parser")

In [14]:
print(soup.prettify())

<p>
 nice try.
 <br/>
 logged.
 <br/>
 bye.
</p>

In [ ]:
bad_request_output = """<p>
 nice try.
 <br/>
 logged.
 <br/>
 bye.
</p>"""